name: 'Namespace'
description: 'Activate a namespace and get the credentials for a Okteto Cloud namespace'
inputs: 
  namespace:
    description: 'The target Kubernetes namespace.'
    required: false
    default: ''
outputs:
  kubeconfig: 
    description: 'The path to the kubeconfig'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.namespace }}