name: "Delete Namespace"
description: "Delete an Okteto Cloud namespace and all its resources"
inputs:
  namespace: 
    description: "The namespace name"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.namespace }}
