name: "Delete Namespace"
description: "Delete an Okteto Cloud namespace"
inputs:
  namespace: 
    description: "The name of the namespace to delete"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.namespace }}