name: 'Deploy'
description: 'Updates manifest with new image and deploys to Okteto Cloud'
inputs: 
  namespace:
    description: 'The target Kubernetes namespace.'
    required: true
  manifest:
    description: 'Path to the Kubernetes manifest.'
    required: false
    default: 'k8s.yml'
  image:
    description: 'Docker image to update.'
    required: true
  tag:
    description: 'The new tag.'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.namespace }}
    - ${{ inputs.manifests }}
    - ${{ inputs.image }}
    - ${{ inputs.tag }}