name: 'Deploy'
description: 'Updates manifest with new image and deploys to Okteto Cloud'
inputs: 
  namespace:
    description: 'The target Kubernetes namespace.'
    required: true
  manifest:
    description: 'Path to the Kubernetes manifest.'
    required: false
    default: 'k8s.yml'
  tag:
    description: 'Name and optionally a tag in the "name:tag" format'
    required: true
  waitOn:
    description: 'Wait until this resource is ready. Must follow the "resource/name" format'
    required: false
  registry:
    description: 'Use registry for pushing to a custom registry'
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.namespace }}
    - ${{ inputs.manifest }}
    - ${{ inputs.tag }}
    - ${{ inputs.waitOn }}
    - ${{ inputs.registry }}
