name: "Create Namespace"
description: "Create a namespace in Okteto Cloud"
inputs:
  namespace: 
    description: "The name of the namespace"
    required: true
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.namespace }}