name: "Push"
description: "Build, push and deploy your changes to Okteto Cloud"
inputs:
  namespace: 
    description: 'If present, the namespace scope for this action. If not specified, it will use the current context'
    required: false
  name: 
    description: "The name of the deployment. If missing it will use the one in your okteto.yml file"
    required: false
  deploy: 
    description: "Create the deployment if it doesn't exist in the namespace. If not specified, the action will fail if the deployment doesn't exist"
    required: false
    default: 'false'
  working-directory:
    description: "Working directory, defaults to the root of the repo"
    required: false
  
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.namespace }}
    - ${{ inputs.name }}
    - ${{ inputs.deploy }}
    - ${{ inputs.working-directory }}